config/routes.rb
Rails.application.routes.draw do
  root to: 'tops#index'
  resources :topics do
    resources :favorites, only: [:create, :destroy]
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show] do 
    resources :favorites, only: [:index]
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  mount_uploader :image, ImageUploader
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
             format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :topics
  has_many :favorites, dependent: :destroy
  has_many :topics, through: :favorites
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    @favorite = current_user.favorites.create(topic_id: params[:topic_id])
    redirect_to topic_path(params[:topic_id]), notice: "#{@favorite.topic.user.name}'s topic add to the Favorites."
  end
  
  def index
    @topics = current_user.favorites.map(&:topic)
  end
  
  def destroy
    @favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to topic_path(params[:topic_id]), notice: "#{@favorite.topic.user.name}'s topic removed from the Favorites."
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'The login attempt failed.'
      render 'new'
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'Logged off.'
    redirect_to new_session_path
  end
  
  private
  
  def session_params
    params.require(:session).permit(:name, :email, :password,
                                      :password_confirmation)
  end                                    
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :require_login
  
  def index
    @topics = Topic.all
  end
  
  def new
    if params[:back]
      @topic = Topic.new(topic_params)
    else
      @topic = Topic.new
    end
  end
  
  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id
    if @topic.save
      TopicMailer.topic_mail(@topic).deliver
      redirect_to topics_path,notice:"topic posted!!"
    else
      render'new'
    end
  end
  
  def show
    @topic = Topic.find(params[:id])
    @favorite = current_user.favorites.find_by(topic_id:@topic.id)
  end
  
  def edit
    @topic = Topic.find(params[:id])
  end
  
  def confirm
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id
    render :new if @topic.invalid?
  end
  
  def update
    @topic = Topic.find(params[:id])
    if @topic.update(topic_params)
      redirect_to topics_path, notice:'topic updated !'
    else
      render'edit'
    end
  end
  
  def destroy
    @topic.destroy
    redirect_to topics_path, notice:'topic deleted.'
  end
  
  private
  
  def topic_params
    params.require(:topic).permit(:content, :image, :image_cache)
  end
  
  def set_topic
    @topic = Topic.find(params[:id])
  end
  
  def require_login
    unless logged_in?
      redirect_to new_session_path
    end
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if@user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end
  
  def show
    @user = User.find(params[:id])
    # @favorites_topics = @user.topics
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password,
                    :password_confirmation,
                    :image, :image_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user.present?
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_topics_path
    elsif action_name == 'edit'
     topic_path
    end
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<h1>favorite page</h1>

<% @topics.each do |topic| %>
 <p>topic : <%= topic.content %></p>
 <p>user name : <%= topic.user.name %></p>
 <p><%= image_tag topic.image %></p>
 
 <div class="topic_links">
  <p><%= link_to 'confirm the details', topic_path(topic.id), class: 'btn btn-default' %>
     <% if topic.user_id == current_user.id %>
      <%= link_to 'update a topic', edit_topic_path(topic.id), data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %>
      <%= link_to 'to delete a topic', topic_path(topic.id), method: :delete ,data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %>
  </p>
 <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
   <title>Kanamogram</title>
   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   <%= csrf_meta_tags %>
   <meta name="viewport" content="width=device-width">
  </head>
  <body>
   <header>
    <ul>
      <nav class="navbar navbar-default">
        <!--<div class="container-fluid">-->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
              <span class="sr-only">Kanamogram</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
    <ul/>        
     <a class="navbar-brand" href="#">kanamogram</a>
     </div>
     <div id="gnavi" class="collapse navbar-collapse">
       <ul class="nav bar-nav mr-auto">
        
    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "favorite", user_favorites_path(current_user.id) %>
      <%= link_to "New post", new_topic_path %>
      <%= link_to "Index", topics_path %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    
       </ul> 
    </div>
   </header>
   
   <section class="main-header">
    <%= image_tag"_DSC4098.jpg", class:"image_area" %> 
   </section>

  <% flash.each do |key, value| %>
   <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
   
  <%= yield %>
   
   <footer>
    <p> 2 0 1 8 June tomko kanamori</p>
   </footer>
   
  </body>
</html>

app/views/topics/_form.html.erb
<%= form_with(model: @topic, local: true ,url: choose_new_or_edit ) do |form| %>
 <% if @topic.errors.any? %>
  <div id="error_explanation">
   <!--<h2><%= @topic.errors.count %>件のエラーがあります。</h2>-->
   <ul>

   <% @topic.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
   <% end %>
   </ul>
  </div>
<% end %>
  
 <div class="topic_content">
  <p><%= form.label :content %></p>
  <p><%= form.text_field :content %></p>
 </div>
 <div class="field">
  <p><%= form.label :image %></p>
  <p><%= image_tag(@topic.image.url) if @topic.image.present? %></p>
  <p><%= form.file_field :image %></p>
  <p><%= form.hidden_field :image_cache %></p>
 </div>
 <div class="actions">
  <p><%= form.submit %></p>
 </div>
<% end %>
<%= link_to "back to index", topics_path, class: 'btn btn-danger btn-lg' %>

app/views/topics/confirm.html.erb
<h3>In the following content, to post..</h3>

<%= form_with(model: @topic, url:topics_path, local: true) do |form| %>
 <%= form.hidden_field :content %>
 <%= image_tag(@topic.image.url) %>
 <%= form.hidden_field :image_cache %>
 
 <P>content:<%= @topic.content %></P>
 <%= form.submit 'post' %>
<% end %>
 
<%= form_with(model: @topic, url:new_topic_path, local: true, method: 'get') do |form| %>
 <%= form.hidden_field :content %>
 <%= form.hidden_field :image_cache %>
 <%= form.submit 'back', name: 'back'%>
<% end %>

app/views/topics/edit.html.erb
<h3>Write a post !</h3>

<%= render 'form' %>

app/views/topics/index.html.erb
<div class="container">
<h1>Topics index</h1><br>

<h3>content</h3>
<!--<p><%= notice %></p><br>-->

 <% @topics.each do |topic| %>
 <p>topic : <%= topic.content %></p>
 <p>user name : <%= topic.user.name %></p>
 <p><%= image_tag topic.image %></p>
 
 <div class="topic_links">
  <p><%= link_to 'confirm the details', topic_path(topic.id), class: 'btn btn-default' %>
     <% if topic.user_id == current_user.id %>
      <%= link_to 'update a topic', edit_topic_path(topic.id), data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %>
      <%= link_to 'to delete a topic', topic_path(topic.id), method: :delete ,data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %>
  </p>
 <% end %>
<% end %> 
 </div>
<br>
 <div class="low">
  <%= link_to 'Topic new post !!', new_topic_path, class: 'btn btn-danger btn-lg' %>
<br>
<br>
 </div>
</div>

app/views/topics/new.html.erb
<div class="form">
<h3>Write a new post !</h3><br>
<%= render 'form' %>
</div>

app/views/topics/show.html.erb
<h3>Topic details</h3>

<p><%= @topic.content %></p>

<p><%= image_tag(@topic.image.url) if @topic.image.url %></p>

<% unless @topic.user_id == current_user.id %>
 <% if @favorite.present? %>
  <%= link_to 'Remove a topic from the Favorites', "/topics/#{@topic.id}/favorites/#{@favorite.id}", method: :delete, class: 'btn btn-default' %>
 <% else %>
  <%= link_to 'Add a Topic to the Favorites', topic_favorites_path(@topic.id), method: :post, class: 'btn btn-default' %>
 <% end %>
<% end %>

app/views/tops/index.html.erb
<div class="container">
 <header class="header">
  <p>Share your moments.</p>
  <p>Discover what you really are interested in.</p>
 </header>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1><br>
<%= form_with(model: @user, local: true) do |f| %>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
   
  <p><%= f.label :name %></p>
  <p><%= f.text_field :name %></p>

  <p><%= f.label :email %></p>
  <p><%= f.email_field :email %></p>
   
  <p><%= f.label :password %></p>
  <p><%= f.password_field :password %></p>
 
  <p><%= f.label :password_confirmation %></p>
  <p><%= f.password_field :password_confirmation %></p>
  
  <p><%= f.label :image %></p>
  <p><%= f.file_field :image %></p><br>
  
<div class="inputbotten">
  <p><%= f.submit "Create my account" %></p>
</div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>'s page</h1>

<p>mail address: <%= @user.email %></p>

<p><%= image_tag(@user.image.url) if @user.image.url %></p>

<!--<p>my favorite :<% @user.topics.each do |topic| %><%= link_to topic.content, topic_path(topic.id) %></p>-->
<% end %>